# ip-pool.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
  namespace: kube-system
spec:
  blocks:
    # - cidr: <-- VALID CIDR RANGE FOR YOUR NETWORK -->
    - start: 10.0.6.0
      stop: 10.0.6.250
