apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  info: 
    - name: "Description"
      value: "The root app that forms the app of app pattern - all other apps are children"
  source:
    repoURL: https://github.com/brian-provenzano/home-cluster.git
    path: argocd/applications/root-app/
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true