apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  info: 
     - name: "Description"
       value: "Traefik Ingress Controller"
  source:
    repoURL: https://traefik.github.io/charts # chart repo
    chart: traefik # chart name
    targetRevision: 28.3.0  # chart version
    helm:
      values: |
        # Default values for Traefik
        deployment:
          # -- Enable deployment
          enabled: true
          # -- Deployment or DaemonSet
          kind: Deployment
          # -- Number of pods of the deployment (only applies when kind == Deployment)
          replicas: 1

        # -- Create a default IngressClass for Traefik
        ingressClass:
          enabled: true
          isDefaultClass: true

        priorityClassName: "application-cluster-critical"

        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            memory: 384Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
    automated:
      prune: true
      selfHeal: true